// Code generated by ts2go. DO NOT EDIT.

package grammars

import "github.com/odvcencio/gotreesitter"

// DamlLanguage returns the daml language definition.
func DamlLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("daml.bin")
}
