// Code generated by ts2go. DO NOT EDIT.

package grammars

import "github.com/odvcencio/gotreesitter"

// FuncLanguage returns the func language definition.
func FuncLanguage() *gotreesitter.Language {
	return loadEmbeddedLanguage("func.bin")
}
